/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SSAbdullakhBenefitsBots, } from "./components/cnt-flexy-view-abdullakh-bot-performance-and-benefits/res/view/cnt-flexy-view-abdullakh-bot-performance-and-benefits_/res/view/cnt-flexy-view-abdullakh-bot-benefits-bots/interface/common.interface";
import { SSAbdullakhConsultation, } from "./components/cnt-flexy-view-abdullakh-bot-consultation/res/view/cnt-flexy-view-abdullakh-bot-consultation_/interface/common.interface";
import { AbdullakhBotForm, } from "./components/cnt-flexy-view-abdullakh-bot-form-communication/res/view/cnt-flexy-view-abdullakh-bot-form-communication/res/view/cnt-flexy-view-abdullakh-bot-form/interface/common.interface";
import { AbdullakhBotFormCommunication, } from "./components/cnt-flexy-view-abdullakh-bot-form-communication/res/view/cnt-flexy-view-abdullakh-bot-form-communication/interface/common.interface";
import { AbdullakhHeaderCenter, } from "./components/cnt-flexy-view-abdullakh-bot-header/res/view/cnt-flexy-view-abdullakh-bot-header_/res/view/cnt-flexy-view-abdullakh-bot-header-center/interface/common.interface";
import { CntFlexyViewCategoryForOwnerItemInterface, } from "./components/cnt-flexy-view-abdullakh-bot-header/res/view/cnt-flexy-view-abdullakh-bot-header_/interface/common.interface";
import { SSAbdullakhPerformanceInformation, } from "./components/cnt-flexy-view-abdullakh-bot-performance-and-benefits/res/view/cnt-flexy-view-abdullakh-bot-performance-and-benefits_/res/view/cnt-flexy-view-abdullakh-bot-performance-information/interface/common.interface";
import { SSAbdullakhProductInformation, } from "./components/cnt-flexy-view-abdullakh-bot-product-information/res/view/cnt-flexy-view-abdullakh-bot-product-information_/interface/common.interface";
import { SSAbdullakhProductPresentation, } from "./components/cnt-flexy-view-abdullakh-bot-product-presentation/res/view/cnt-flexy-view-abdullakh-bot-product-presentation_/interface/common.interface";
import { SSAbdullakhTransitionCreateBot, } from "./components/cnt-flexy-view-abdullakh-bot-transition-create-bot/res/view/cnt-flexy-view-abdullakh-bot-transition-create-bot_/interface/common.interface";
export namespace Components {
    interface CntFlexyViewAbdullakhBotBenefitsBots {
        /**
          * объект с массивом и данными BenefitsBots
         */
        "BenefitsBots": SSAbdullakhBenefitsBots;
    }
    interface CntFlexyViewAbdullakhBotBenefitsBotsBlock {
        /**
          * данные переданные методом map компоненту BenefitsBotsBlock
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhBotConsultation1_01 {
        "pathToAssets": string;
        /**
          * данные компонента Consultation
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotConsultation_ {
        /**
          * данные компонента Consultation
         */
        "payload": SSAbdullakhConsultation;
    }
    interface CntFlexyViewAbdullakhBotForm {
        /**
          * данные из массива для компонента Form
         */
        "arr": AbdullakhBotForm;
    }
    interface CntFlexyViewAbdullakhBotFormClose {
    }
    interface CntFlexyViewAbdullakhBotFormCommunication1_01 {
        "pathToAssets": string;
        /**
          * данные компонента FormCommunication
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotFormCommunication_ {
        /**
          * данные компонента FormCommunication
         */
        "payload": AbdullakhBotFormCommunication;
    }
    interface CntFlexyViewAbdullakhBotFormInput {
        "phoneMask": any;
    }
    interface CntFlexyViewAbdullakhBotHeader1_01 {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories": any;
        "pathToAssets": string;
    }
    interface CntFlexyViewAbdullakhBotHeaderCenter {
        /**
          * объект с данными и для элементов меню
         */
        "arr": AbdullakhHeaderCenter;
    }
    interface CntFlexyViewAbdullakhBotHeaderEnd {
        /**
          * number
         */
        "phoneNumber": string;
    }
    interface CntFlexyViewAbdullakhBotHeaderStart {
        /**
          * объект с url logo
         */
        "logo": any;
    }
    interface CntFlexyViewAbdullakhBotHeader_ {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories": CntFlexyViewCategoryForOwnerItemInterface;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits1_01 {
        "pathToAssets": string;
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits_ {
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotPerformanceInformation {
        /**
          * массив для вывода элементов PerformanceInformation
         */
        "PerformanceInformation": SSAbdullakhPerformanceInformation;
    }
    interface CntFlexyViewAbdullakhBotPerformanceInformationList {
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "PerformanceInformation": any;
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "endText": string;
    }
    interface CntFlexyViewAbdullakhBotProductInformation1_01 {
        "pathToAssets": string;
        /**
          * данные из объекта для компонента ProductInformation
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotProductInformationBlocks {
        /**
          * объект с данными и для элементов компонента ProductInformationBlocks
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhBotProductInformation_ {
        /**
          * данные из объекта для компонента ProductInformation
         */
        "ProductInformation": SSAbdullakhProductInformation;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation1_01 {
        "pathToAssets": string;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotProductPresentationImg {
        /**
          * массив для вывода url img в компоненете ProductPresentationImg
         */
        "img": any;
    }
    interface CntFlexyViewAbdullakhBotProductPresentationTitle {
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "arr": any;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "img": string;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation_ {
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload": SSAbdullakhProductPresentation;
    }
    interface CntFlexyViewAbdullakhBotTariffs1_01 {
        "pathToAssets": string;
        /**
          * данные компонента Tariffs
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotTariffsInfoBlocks {
        /**
          * данные переданные методом map компоненту TariffsBlocks
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhBotTariffs_ {
        /**
          * данные компонента Tariffs
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot1_01 {
        "pathToAssets": string;
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBotFollow {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotFollow компонента TransitionCreateBot
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBotTitle {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotTitle компонента TransitionCreateBot
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot_ {
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload": SSAbdullakhTransitionCreateBot;
    }
    interface CntFlexyViewAbdullakhUniversalFooter1_01 {
        "categories": any;
    }
    interface CntFlexyViewAbdullakhUniversalFooter_ {
        "footerIcons": any;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLCntFlexyViewAbdullakhBotBenefitsBotsElement extends Components.CntFlexyViewAbdullakhBotBenefitsBots, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotBenefitsBotsElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotBenefitsBotsElement;
        new (): HTMLCntFlexyViewAbdullakhBotBenefitsBotsElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotBenefitsBotsBlockElement extends Components.CntFlexyViewAbdullakhBotBenefitsBotsBlock, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotBenefitsBotsBlockElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotBenefitsBotsBlockElement;
        new (): HTMLCntFlexyViewAbdullakhBotBenefitsBotsBlockElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotConsultation1_01Element extends Components.CntFlexyViewAbdullakhBotConsultation1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotConsultation1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotConsultation1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotConsultation1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotConsultation_Element extends Components.CntFlexyViewAbdullakhBotConsultation_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotConsultation_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotConsultation_Element;
        new (): HTMLCntFlexyViewAbdullakhBotConsultation_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotFormElement extends Components.CntFlexyViewAbdullakhBotForm, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotFormElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotFormElement;
        new (): HTMLCntFlexyViewAbdullakhBotFormElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotFormCloseElement extends Components.CntFlexyViewAbdullakhBotFormClose, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotFormCloseElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotFormCloseElement;
        new (): HTMLCntFlexyViewAbdullakhBotFormCloseElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotFormCommunication1_01Element extends Components.CntFlexyViewAbdullakhBotFormCommunication1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotFormCommunication1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotFormCommunication1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotFormCommunication1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotFormCommunication_Element extends Components.CntFlexyViewAbdullakhBotFormCommunication_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotFormCommunication_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotFormCommunication_Element;
        new (): HTMLCntFlexyViewAbdullakhBotFormCommunication_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotFormInputElement extends Components.CntFlexyViewAbdullakhBotFormInput, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotFormInputElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotFormInputElement;
        new (): HTMLCntFlexyViewAbdullakhBotFormInputElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeader1_01Element extends Components.CntFlexyViewAbdullakhBotHeader1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeader1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeader1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotHeader1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeaderCenterElement extends Components.CntFlexyViewAbdullakhBotHeaderCenter, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeaderCenterElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeaderCenterElement;
        new (): HTMLCntFlexyViewAbdullakhBotHeaderCenterElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeaderEndElement extends Components.CntFlexyViewAbdullakhBotHeaderEnd, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeaderEndElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeaderEndElement;
        new (): HTMLCntFlexyViewAbdullakhBotHeaderEndElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeaderStartElement extends Components.CntFlexyViewAbdullakhBotHeaderStart, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeaderStartElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeaderStartElement;
        new (): HTMLCntFlexyViewAbdullakhBotHeaderStartElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeader_Element extends Components.CntFlexyViewAbdullakhBotHeader_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeader_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeader_Element;
        new (): HTMLCntFlexyViewAbdullakhBotHeader_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_01Element extends Components.CntFlexyViewAbdullakhBotPerformanceAndBenefits1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits_Element extends Components.CntFlexyViewAbdullakhBotPerformanceAndBenefits_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits_Element;
        new (): HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotPerformanceInformationElement extends Components.CntFlexyViewAbdullakhBotPerformanceInformation, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotPerformanceInformationElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotPerformanceInformationElement;
        new (): HTMLCntFlexyViewAbdullakhBotPerformanceInformationElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotPerformanceInformationListElement extends Components.CntFlexyViewAbdullakhBotPerformanceInformationList, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotPerformanceInformationListElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotPerformanceInformationListElement;
        new (): HTMLCntFlexyViewAbdullakhBotPerformanceInformationListElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductInformation1_01Element extends Components.CntFlexyViewAbdullakhBotProductInformation1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductInformation1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductInformation1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotProductInformation1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement extends Components.CntFlexyViewAbdullakhBotProductInformationBlocks, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement;
        new (): HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductInformation_Element extends Components.CntFlexyViewAbdullakhBotProductInformation_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductInformation_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductInformation_Element;
        new (): HTMLCntFlexyViewAbdullakhBotProductInformation_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductPresentation1_01Element extends Components.CntFlexyViewAbdullakhBotProductPresentation1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductPresentation1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductPresentation1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotProductPresentation1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductPresentationImgElement extends Components.CntFlexyViewAbdullakhBotProductPresentationImg, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductPresentationImgElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductPresentationImgElement;
        new (): HTMLCntFlexyViewAbdullakhBotProductPresentationImgElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductPresentationTitleElement extends Components.CntFlexyViewAbdullakhBotProductPresentationTitle, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductPresentationTitleElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductPresentationTitleElement;
        new (): HTMLCntFlexyViewAbdullakhBotProductPresentationTitleElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductPresentation_Element extends Components.CntFlexyViewAbdullakhBotProductPresentation_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductPresentation_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductPresentation_Element;
        new (): HTMLCntFlexyViewAbdullakhBotProductPresentation_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotTariffs1_01Element extends Components.CntFlexyViewAbdullakhBotTariffs1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTariffs1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotTariffs1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotTariffs1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotTariffsInfoBlocksElement extends Components.CntFlexyViewAbdullakhBotTariffsInfoBlocks, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTariffsInfoBlocksElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotTariffsInfoBlocksElement;
        new (): HTMLCntFlexyViewAbdullakhBotTariffsInfoBlocksElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotTariffs_Element extends Components.CntFlexyViewAbdullakhBotTariffs_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTariffs_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotTariffs_Element;
        new (): HTMLCntFlexyViewAbdullakhBotTariffs_Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_01Element extends Components.CntFlexyViewAbdullakhBotTransitionCreateBot1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_01Element;
        new (): HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotTransitionCreateBotFollowElement extends Components.CntFlexyViewAbdullakhBotTransitionCreateBotFollow, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTransitionCreateBotFollowElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotTransitionCreateBotFollowElement;
        new (): HTMLCntFlexyViewAbdullakhBotTransitionCreateBotFollowElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotTransitionCreateBotTitleElement extends Components.CntFlexyViewAbdullakhBotTransitionCreateBotTitle, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTransitionCreateBotTitleElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotTransitionCreateBotTitleElement;
        new (): HTMLCntFlexyViewAbdullakhBotTransitionCreateBotTitleElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotTransitionCreateBot_Element extends Components.CntFlexyViewAbdullakhBotTransitionCreateBot_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTransitionCreateBot_Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotTransitionCreateBot_Element;
        new (): HTMLCntFlexyViewAbdullakhBotTransitionCreateBot_Element;
    };
    interface HTMLCntFlexyViewAbdullakhUniversalFooter1_01Element extends Components.CntFlexyViewAbdullakhUniversalFooter1_01, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhUniversalFooter1_01Element: {
        prototype: HTMLCntFlexyViewAbdullakhUniversalFooter1_01Element;
        new (): HTMLCntFlexyViewAbdullakhUniversalFooter1_01Element;
    };
    interface HTMLCntFlexyViewAbdullakhUniversalFooter_Element extends Components.CntFlexyViewAbdullakhUniversalFooter_, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhUniversalFooter_Element: {
        prototype: HTMLCntFlexyViewAbdullakhUniversalFooter_Element;
        new (): HTMLCntFlexyViewAbdullakhUniversalFooter_Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-abdullakh-bot-benefits-bots": HTMLCntFlexyViewAbdullakhBotBenefitsBotsElement;
        "cnt-flexy-view-abdullakh-bot-benefits-bots-block": HTMLCntFlexyViewAbdullakhBotBenefitsBotsBlockElement;
        "cnt-flexy-view-abdullakh-bot-consultation-1_01": HTMLCntFlexyViewAbdullakhBotConsultation1_01Element;
        "cnt-flexy-view-abdullakh-bot-consultation_": HTMLCntFlexyViewAbdullakhBotConsultation_Element;
        "cnt-flexy-view-abdullakh-bot-form": HTMLCntFlexyViewAbdullakhBotFormElement;
        "cnt-flexy-view-abdullakh-bot-form-close": HTMLCntFlexyViewAbdullakhBotFormCloseElement;
        "cnt-flexy-view-abdullakh-bot-form-communication-1_01": HTMLCntFlexyViewAbdullakhBotFormCommunication1_01Element;
        "cnt-flexy-view-abdullakh-bot-form-communication_": HTMLCntFlexyViewAbdullakhBotFormCommunication_Element;
        "cnt-flexy-view-abdullakh-bot-form-input": HTMLCntFlexyViewAbdullakhBotFormInputElement;
        "cnt-flexy-view-abdullakh-bot-header-1_01": HTMLCntFlexyViewAbdullakhBotHeader1_01Element;
        "cnt-flexy-view-abdullakh-bot-header-center": HTMLCntFlexyViewAbdullakhBotHeaderCenterElement;
        "cnt-flexy-view-abdullakh-bot-header-end": HTMLCntFlexyViewAbdullakhBotHeaderEndElement;
        "cnt-flexy-view-abdullakh-bot-header-start": HTMLCntFlexyViewAbdullakhBotHeaderStartElement;
        "cnt-flexy-view-abdullakh-bot-header_": HTMLCntFlexyViewAbdullakhBotHeader_Element;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_01": HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_01Element;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits_": HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits_Element;
        "cnt-flexy-view-abdullakh-bot-performance-information": HTMLCntFlexyViewAbdullakhBotPerformanceInformationElement;
        "cnt-flexy-view-abdullakh-bot-performance-information-list": HTMLCntFlexyViewAbdullakhBotPerformanceInformationListElement;
        "cnt-flexy-view-abdullakh-bot-product-information-1_01": HTMLCntFlexyViewAbdullakhBotProductInformation1_01Element;
        "cnt-flexy-view-abdullakh-bot-product-information-blocks": HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement;
        "cnt-flexy-view-abdullakh-bot-product-information_": HTMLCntFlexyViewAbdullakhBotProductInformation_Element;
        "cnt-flexy-view-abdullakh-bot-product-presentation-1_01": HTMLCntFlexyViewAbdullakhBotProductPresentation1_01Element;
        "cnt-flexy-view-abdullakh-bot-product-presentation-img": HTMLCntFlexyViewAbdullakhBotProductPresentationImgElement;
        "cnt-flexy-view-abdullakh-bot-product-presentation-title": HTMLCntFlexyViewAbdullakhBotProductPresentationTitleElement;
        "cnt-flexy-view-abdullakh-bot-product-presentation_": HTMLCntFlexyViewAbdullakhBotProductPresentation_Element;
        "cnt-flexy-view-abdullakh-bot-tariffs-1_01": HTMLCntFlexyViewAbdullakhBotTariffs1_01Element;
        "cnt-flexy-view-abdullakh-bot-tariffs-info-blocks": HTMLCntFlexyViewAbdullakhBotTariffsInfoBlocksElement;
        "cnt-flexy-view-abdullakh-bot-tariffs_": HTMLCntFlexyViewAbdullakhBotTariffs_Element;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-1_01": HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_01Element;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-follow": HTMLCntFlexyViewAbdullakhBotTransitionCreateBotFollowElement;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-title": HTMLCntFlexyViewAbdullakhBotTransitionCreateBotTitleElement;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot_": HTMLCntFlexyViewAbdullakhBotTransitionCreateBot_Element;
        "cnt-flexy-view-abdullakh-universal-footer-1_01": HTMLCntFlexyViewAbdullakhUniversalFooter1_01Element;
        "cnt-flexy-view-abdullakh-universal-footer_": HTMLCntFlexyViewAbdullakhUniversalFooter_Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewAbdullakhBotBenefitsBots {
        /**
          * объект с массивом и данными BenefitsBots
         */
        "BenefitsBots"?: SSAbdullakhBenefitsBots;
        /**
          * клик по элементам компонента BenefitsBots
         */
        "onClickOnBenefitsBots"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotBenefitsBotsBlock {
        /**
          * данные переданные методом map компоненту BenefitsBotsBlock
         */
        "arr"?: any;
        /**
          * клик по элементам компонента BenefitsBots
         */
        "onClickOnBenefitsBots"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotConsultation1_01 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные компонента Consultation
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotConsultation_ {
        /**
          * клик по элементам компонента Consultation
         */
        "onClickOnConsultation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * данные компонента Consultation
         */
        "payload"?: SSAbdullakhConsultation;
    }
    interface CntFlexyViewAbdullakhBotForm {
        /**
          * данные из массива для компонента Form
         */
        "arr"?: AbdullakhBotForm;
    }
    interface CntFlexyViewAbdullakhBotFormClose {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotFormCommunication1_01 {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные компонента FormCommunication
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotFormCommunication_ {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        /**
          * данные компонента FormCommunication
         */
        "payload"?: AbdullakhBotFormCommunication;
    }
    interface CntFlexyViewAbdullakhBotFormInput {
        "phoneMask"?: any;
    }
    interface CntFlexyViewAbdullakhBotHeader1_01 {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories"?: any;
        "pathToAssets"?: string;
    }
    interface CntFlexyViewAbdullakhBotHeaderCenter {
        /**
          * объект с данными и для элементов меню
         */
        "arr"?: AbdullakhHeaderCenter;
        /**
          * клик по элементу HeaderCenter (меню) компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotHeaderEnd {
        /**
          * клик по элементy HeaderEnd компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
        /**
          * number
         */
        "phoneNumber"?: string;
    }
    interface CntFlexyViewAbdullakhBotHeaderStart {
        /**
          * объект с url logo
         */
        "logo"?: any;
        /**
          * клик по элементу HeaderStart компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotHeader_ {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories"?: CntFlexyViewCategoryForOwnerItemInterface;
        /**
          * клик по элементам компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits1_01 {
        /**
          * открытие формы связи
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits_ {
        /**
          * клик по элементам компонента PerformanceAndBenefits
         */
        "onClickOnPerformanceAndBenefits"?: (event: CustomEvent<any>) => void;
        /**
          * открытие формы связи
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotPerformanceInformation {
        /**
          * массив для вывода элементов PerformanceInformation
         */
        "PerformanceInformation"?: SSAbdullakhPerformanceInformation;
        /**
          * клик по элементам компонента PerformanceInformation
         */
        "onClickOnPerformanceInformation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotPerformanceInformationList {
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "PerformanceInformation"?: any;
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "endText"?: string;
        /**
          * клик по элементам компонента PerformanceInformation подкомпонента PerformanceInformationList
         */
        "onClickOnPerformanceInformation"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductInformation1_01 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные из объекта для компонента ProductInformation
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotProductInformationBlocks {
        /**
          * объект с данными и для элементов компонента ProductInformationBlocks
         */
        "arr"?: any;
        /**
          * клик по элементам компонента ProductInformation
         */
        "onClickOnProductInformation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductInformation_ {
        /**
          * данные из объекта для компонента ProductInformation
         */
        "ProductInformation"?: SSAbdullakhProductInformation;
        /**
          * клик по элементам компонента ProductInformation
         */
        "onClickOnProductInformation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation1_01 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotProductPresentationImg {
        /**
          * массив для вывода url img в компоненете ProductPresentationImg
         */
        "img"?: any;
        /**
          * клик по элементам подкомпонента ProductPresentationImg компонента ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductPresentationTitle {
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "arr"?: any;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "img"?: string;
        /**
          * клик по элементам компонента ProductPresentation подкомпонента ProductPresentationTitle
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation_ {
        /**
          * клик по элементам компонента ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload"?: SSAbdullakhProductPresentation;
    }
    interface CntFlexyViewAbdullakhBotTariffs1_01 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные компонента Tariffs
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotTariffsInfoBlocks {
        /**
          * данные переданные методом map компоненту TariffsBlocks
         */
        "arr"?: any;
        /**
          * клик по элементам компонента Tariffs
         */
        "onClickOnTariffs"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotTariffs_ {
        /**
          * клик по элементам компонента Tariffs
         */
        "onClickOnTariffs"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * данные компонента Tariffs
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot1_01 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBotFollow {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotFollow компонента TransitionCreateBot
         */
        "arr"?: any;
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnTransitionCreateBot"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBotTitle {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotTitle компонента TransitionCreateBot
         */
        "arr"?: any;
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnTransitionCreateBot"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot_ {
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnTransitionCreateBot"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload"?: SSAbdullakhTransitionCreateBot;
    }
    interface CntFlexyViewAbdullakhUniversalFooter1_01 {
        "categories"?: any;
    }
    interface CntFlexyViewAbdullakhUniversalFooter_ {
        "footerIcons"?: any;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "cnt-flexy-view-abdullakh-bot-benefits-bots": CntFlexyViewAbdullakhBotBenefitsBots;
        "cnt-flexy-view-abdullakh-bot-benefits-bots-block": CntFlexyViewAbdullakhBotBenefitsBotsBlock;
        "cnt-flexy-view-abdullakh-bot-consultation-1_01": CntFlexyViewAbdullakhBotConsultation1_01;
        "cnt-flexy-view-abdullakh-bot-consultation_": CntFlexyViewAbdullakhBotConsultation_;
        "cnt-flexy-view-abdullakh-bot-form": CntFlexyViewAbdullakhBotForm;
        "cnt-flexy-view-abdullakh-bot-form-close": CntFlexyViewAbdullakhBotFormClose;
        "cnt-flexy-view-abdullakh-bot-form-communication-1_01": CntFlexyViewAbdullakhBotFormCommunication1_01;
        "cnt-flexy-view-abdullakh-bot-form-communication_": CntFlexyViewAbdullakhBotFormCommunication_;
        "cnt-flexy-view-abdullakh-bot-form-input": CntFlexyViewAbdullakhBotFormInput;
        "cnt-flexy-view-abdullakh-bot-header-1_01": CntFlexyViewAbdullakhBotHeader1_01;
        "cnt-flexy-view-abdullakh-bot-header-center": CntFlexyViewAbdullakhBotHeaderCenter;
        "cnt-flexy-view-abdullakh-bot-header-end": CntFlexyViewAbdullakhBotHeaderEnd;
        "cnt-flexy-view-abdullakh-bot-header-start": CntFlexyViewAbdullakhBotHeaderStart;
        "cnt-flexy-view-abdullakh-bot-header_": CntFlexyViewAbdullakhBotHeader_;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_01": CntFlexyViewAbdullakhBotPerformanceAndBenefits1_01;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits_": CntFlexyViewAbdullakhBotPerformanceAndBenefits_;
        "cnt-flexy-view-abdullakh-bot-performance-information": CntFlexyViewAbdullakhBotPerformanceInformation;
        "cnt-flexy-view-abdullakh-bot-performance-information-list": CntFlexyViewAbdullakhBotPerformanceInformationList;
        "cnt-flexy-view-abdullakh-bot-product-information-1_01": CntFlexyViewAbdullakhBotProductInformation1_01;
        "cnt-flexy-view-abdullakh-bot-product-information-blocks": CntFlexyViewAbdullakhBotProductInformationBlocks;
        "cnt-flexy-view-abdullakh-bot-product-information_": CntFlexyViewAbdullakhBotProductInformation_;
        "cnt-flexy-view-abdullakh-bot-product-presentation-1_01": CntFlexyViewAbdullakhBotProductPresentation1_01;
        "cnt-flexy-view-abdullakh-bot-product-presentation-img": CntFlexyViewAbdullakhBotProductPresentationImg;
        "cnt-flexy-view-abdullakh-bot-product-presentation-title": CntFlexyViewAbdullakhBotProductPresentationTitle;
        "cnt-flexy-view-abdullakh-bot-product-presentation_": CntFlexyViewAbdullakhBotProductPresentation_;
        "cnt-flexy-view-abdullakh-bot-tariffs-1_01": CntFlexyViewAbdullakhBotTariffs1_01;
        "cnt-flexy-view-abdullakh-bot-tariffs-info-blocks": CntFlexyViewAbdullakhBotTariffsInfoBlocks;
        "cnt-flexy-view-abdullakh-bot-tariffs_": CntFlexyViewAbdullakhBotTariffs_;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-1_01": CntFlexyViewAbdullakhBotTransitionCreateBot1_01;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-follow": CntFlexyViewAbdullakhBotTransitionCreateBotFollow;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-title": CntFlexyViewAbdullakhBotTransitionCreateBotTitle;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot_": CntFlexyViewAbdullakhBotTransitionCreateBot_;
        "cnt-flexy-view-abdullakh-universal-footer-1_01": CntFlexyViewAbdullakhUniversalFooter1_01;
        "cnt-flexy-view-abdullakh-universal-footer_": CntFlexyViewAbdullakhUniversalFooter_;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-abdullakh-bot-benefits-bots": LocalJSX.CntFlexyViewAbdullakhBotBenefitsBots & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotBenefitsBotsElement>;
            "cnt-flexy-view-abdullakh-bot-benefits-bots-block": LocalJSX.CntFlexyViewAbdullakhBotBenefitsBotsBlock & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotBenefitsBotsBlockElement>;
            "cnt-flexy-view-abdullakh-bot-consultation-1_01": LocalJSX.CntFlexyViewAbdullakhBotConsultation1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotConsultation1_01Element>;
            "cnt-flexy-view-abdullakh-bot-consultation_": LocalJSX.CntFlexyViewAbdullakhBotConsultation_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotConsultation_Element>;
            "cnt-flexy-view-abdullakh-bot-form": LocalJSX.CntFlexyViewAbdullakhBotForm & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotFormElement>;
            "cnt-flexy-view-abdullakh-bot-form-close": LocalJSX.CntFlexyViewAbdullakhBotFormClose & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotFormCloseElement>;
            "cnt-flexy-view-abdullakh-bot-form-communication-1_01": LocalJSX.CntFlexyViewAbdullakhBotFormCommunication1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotFormCommunication1_01Element>;
            "cnt-flexy-view-abdullakh-bot-form-communication_": LocalJSX.CntFlexyViewAbdullakhBotFormCommunication_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotFormCommunication_Element>;
            "cnt-flexy-view-abdullakh-bot-form-input": LocalJSX.CntFlexyViewAbdullakhBotFormInput & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotFormInputElement>;
            "cnt-flexy-view-abdullakh-bot-header-1_01": LocalJSX.CntFlexyViewAbdullakhBotHeader1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeader1_01Element>;
            "cnt-flexy-view-abdullakh-bot-header-center": LocalJSX.CntFlexyViewAbdullakhBotHeaderCenter & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeaderCenterElement>;
            "cnt-flexy-view-abdullakh-bot-header-end": LocalJSX.CntFlexyViewAbdullakhBotHeaderEnd & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeaderEndElement>;
            "cnt-flexy-view-abdullakh-bot-header-start": LocalJSX.CntFlexyViewAbdullakhBotHeaderStart & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeaderStartElement>;
            "cnt-flexy-view-abdullakh-bot-header_": LocalJSX.CntFlexyViewAbdullakhBotHeader_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeader_Element>;
            "cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_01": LocalJSX.CntFlexyViewAbdullakhBotPerformanceAndBenefits1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_01Element>;
            "cnt-flexy-view-abdullakh-bot-performance-and-benefits_": LocalJSX.CntFlexyViewAbdullakhBotPerformanceAndBenefits_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits_Element>;
            "cnt-flexy-view-abdullakh-bot-performance-information": LocalJSX.CntFlexyViewAbdullakhBotPerformanceInformation & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotPerformanceInformationElement>;
            "cnt-flexy-view-abdullakh-bot-performance-information-list": LocalJSX.CntFlexyViewAbdullakhBotPerformanceInformationList & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotPerformanceInformationListElement>;
            "cnt-flexy-view-abdullakh-bot-product-information-1_01": LocalJSX.CntFlexyViewAbdullakhBotProductInformation1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductInformation1_01Element>;
            "cnt-flexy-view-abdullakh-bot-product-information-blocks": LocalJSX.CntFlexyViewAbdullakhBotProductInformationBlocks & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement>;
            "cnt-flexy-view-abdullakh-bot-product-information_": LocalJSX.CntFlexyViewAbdullakhBotProductInformation_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductInformation_Element>;
            "cnt-flexy-view-abdullakh-bot-product-presentation-1_01": LocalJSX.CntFlexyViewAbdullakhBotProductPresentation1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductPresentation1_01Element>;
            "cnt-flexy-view-abdullakh-bot-product-presentation-img": LocalJSX.CntFlexyViewAbdullakhBotProductPresentationImg & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductPresentationImgElement>;
            "cnt-flexy-view-abdullakh-bot-product-presentation-title": LocalJSX.CntFlexyViewAbdullakhBotProductPresentationTitle & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductPresentationTitleElement>;
            "cnt-flexy-view-abdullakh-bot-product-presentation_": LocalJSX.CntFlexyViewAbdullakhBotProductPresentation_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductPresentation_Element>;
            "cnt-flexy-view-abdullakh-bot-tariffs-1_01": LocalJSX.CntFlexyViewAbdullakhBotTariffs1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTariffs1_01Element>;
            "cnt-flexy-view-abdullakh-bot-tariffs-info-blocks": LocalJSX.CntFlexyViewAbdullakhBotTariffsInfoBlocks & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTariffsInfoBlocksElement>;
            "cnt-flexy-view-abdullakh-bot-tariffs_": LocalJSX.CntFlexyViewAbdullakhBotTariffs_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTariffs_Element>;
            "cnt-flexy-view-abdullakh-bot-transition-create-bot-1_01": LocalJSX.CntFlexyViewAbdullakhBotTransitionCreateBot1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_01Element>;
            "cnt-flexy-view-abdullakh-bot-transition-create-bot-follow": LocalJSX.CntFlexyViewAbdullakhBotTransitionCreateBotFollow & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTransitionCreateBotFollowElement>;
            "cnt-flexy-view-abdullakh-bot-transition-create-bot-title": LocalJSX.CntFlexyViewAbdullakhBotTransitionCreateBotTitle & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTransitionCreateBotTitleElement>;
            "cnt-flexy-view-abdullakh-bot-transition-create-bot_": LocalJSX.CntFlexyViewAbdullakhBotTransitionCreateBot_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTransitionCreateBot_Element>;
            "cnt-flexy-view-abdullakh-universal-footer-1_01": LocalJSX.CntFlexyViewAbdullakhUniversalFooter1_01 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhUniversalFooter1_01Element>;
            "cnt-flexy-view-abdullakh-universal-footer_": LocalJSX.CntFlexyViewAbdullakhUniversalFooter_ & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhUniversalFooter_Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
