/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SSAbdullakhConsultation, } from "./components/cnt-flexy-view-abdullakh-bot-consultation-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-consultation/interface/common.interface";
import { CntFlexyViewCategoryForOwnerItemInterface, } from "./components/cnt-flexy-view-abdullakh-bot-header-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-header/interface/common.interface";
import { SSAbdullakhProductInformation, } from "./components/cnt-flexy-view-abdullakh-bot-product-information-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-product-information/interface/common.interface";
import { SSAbdullakhProductPresentation, } from "./components/cnt-flexy-view-abdullakh-bot-product-presentation-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-product-presentation/interface/common.interface";
import { SSAbdullakhTransitionCreateBot, } from "./components/cnt-flexy-view-abdullakh-bot-transition-create-bot-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-transition-create-bot/interface/common.interface";
import { SSAbdullakhBenefitsBots, } from "./components/cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-performance-and-benefits/res/view/s-abdullakh-benefits-bots/interface/common.interface";
import { AbdullakhHeaderCenter, } from "./components/cnt-flexy-view-abdullakh-bot-header-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-header/res/view/s-abdullakh-header-center/interface/common.interface";
import { SSAbdullakhPerformanceInformation, } from "./components/cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_0_0/res/view/cnt-flexy-view-abdullakh-bot-performance-and-benefits/res/view/s-abdullakh-performance-information/interface/common.interface";
export namespace Components {
    interface CntFlexyViewAbdullakhBotConsultation {
        /**
          * данные компонента Consultation
         */
        "payload": SSAbdullakhConsultation;
    }
    interface CntFlexyViewAbdullakhBotConsultation1_0_0 {
        "pathToAssets": string;
        /**
          * данные компонента Consultation
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotFormCommunication1_0_0 {
        "pathToAssets": string;
        /**
          * данные компонента FormCommunication
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotHeader {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories": CntFlexyViewCategoryForOwnerItemInterface;
    }
    interface CntFlexyViewAbdullakhBotHeader1_0_0 {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories": any;
        "pathToAssets": string;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits {
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0 {
        "pathToAssets": string;
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotProductInformation {
        /**
          * данные из объекта для компонента ProductInformation
         */
        "ProductInformation": SSAbdullakhProductInformation;
    }
    interface CntFlexyViewAbdullakhBotProductInformation1_0_0 {
        "pathToAssets": string;
        /**
          * данные из объекта для компонента ProductInformation
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotProductInformationBlocks {
        /**
          * объект с данными и для элементов компонента ProductInformationBlocks
         */
        "arr": any;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation {
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload": SSAbdullakhProductPresentation;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation1_0_0 {
        "pathToAssets": string;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotTariffs {
        /**
          * данные компонента Tariffs
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotTariffs1_0_0 {
        "pathToAssets": string;
        /**
          * данные компонента Tariffs
         */
        "payload": any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot {
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload": SSAbdullakhTransitionCreateBot;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot1_0_0 {
        "pathToAssets": string;
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload": any;
    }
    interface CntFlexyViewBotAbdullakhFormCommunication {
        /**
          * данные компонента FormCommunication
         */
        "payload": any;
    }
    interface MyComponent {
    }
    interface SAbdullakhBenefitsBots {
        /**
          * объект с массивом и данными BenefitsBots
         */
        "BenefitsBots": SSAbdullakhBenefitsBots;
    }
    interface SAbdullakhBenefitsBotsBlock {
        /**
          * данные переданные методом map компоненту BenefitsBotsBlock
         */
        "arr": any;
    }
    interface SAbdullakhForm {
        /**
          * данные из массива для компонента Form
         */
        "arr": any;
    }
    interface SAbdullakhFormClose {
    }
    interface SAbdullakhHeaderCenter {
        /**
          * объект с данными и для элементов меню
         */
        "arr": AbdullakhHeaderCenter;
    }
    interface SAbdullakhHeaderEnd {
        /**
          * number
         */
        "phoneNumber": string;
    }
    interface SAbdullakhHeaderStart {
        /**
          * объект с url logo
         */
        "logo": any;
    }
    interface SAbdullakhPerformanceInformation {
        /**
          * массив для вывода элементов PerformanceInformation
         */
        "PerformanceInformation": SSAbdullakhPerformanceInformation;
    }
    interface SAbdullakhPerformanceInformationList {
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "PerformanceInformation": any;
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "endText": string;
    }
    interface SAbdullakhProductPresentationImg {
        /**
          * массив для вывода url img в компоненете ProductPresentationImg
         */
        "img": any;
    }
    interface SAbdullakhProductPresentationTitle {
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "arr": any;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "img": string;
    }
    interface SAbdullakhTariffsInfoBlocks {
        /**
          * данные переданные методом map компоненту TariffsBlocks
         */
        "arr": any;
    }
    interface SAbdullakhTransitionCreateBotFollow {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotFollow компонента TransitionCreateBot
         */
        "arr": any;
    }
    interface SAbdullakhTransitionCreateBotTitle {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotTitle компонента TransitionCreateBot
         */
        "arr": any;
    }
}
declare global {
    interface HTMLCntFlexyViewAbdullakhBotConsultationElement extends Components.CntFlexyViewAbdullakhBotConsultation, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotConsultationElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotConsultationElement;
        new (): HTMLCntFlexyViewAbdullakhBotConsultationElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotConsultation1_0_0Element extends Components.CntFlexyViewAbdullakhBotConsultation1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotConsultation1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotConsultation1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotConsultation1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotFormCommunication1_0_0Element extends Components.CntFlexyViewAbdullakhBotFormCommunication1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotFormCommunication1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotFormCommunication1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotFormCommunication1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeaderElement extends Components.CntFlexyViewAbdullakhBotHeader, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeaderElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeaderElement;
        new (): HTMLCntFlexyViewAbdullakhBotHeaderElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotHeader1_0_0Element extends Components.CntFlexyViewAbdullakhBotHeader1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotHeader1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotHeader1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotHeader1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefitsElement extends Components.CntFlexyViewAbdullakhBotPerformanceAndBenefits, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefitsElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefitsElement;
        new (): HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefitsElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0Element extends Components.CntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductInformationElement extends Components.CntFlexyViewAbdullakhBotProductInformation, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductInformationElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductInformationElement;
        new (): HTMLCntFlexyViewAbdullakhBotProductInformationElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductInformation1_0_0Element extends Components.CntFlexyViewAbdullakhBotProductInformation1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductInformation1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductInformation1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotProductInformation1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement extends Components.CntFlexyViewAbdullakhBotProductInformationBlocks, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement;
        new (): HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductPresentationElement extends Components.CntFlexyViewAbdullakhBotProductPresentation, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductPresentationElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductPresentationElement;
        new (): HTMLCntFlexyViewAbdullakhBotProductPresentationElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotProductPresentation1_0_0Element extends Components.CntFlexyViewAbdullakhBotProductPresentation1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotProductPresentation1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotProductPresentation1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotProductPresentation1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotTariffsElement extends Components.CntFlexyViewAbdullakhBotTariffs, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTariffsElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotTariffsElement;
        new (): HTMLCntFlexyViewAbdullakhBotTariffsElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotTariffs1_0_0Element extends Components.CntFlexyViewAbdullakhBotTariffs1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTariffs1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotTariffs1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotTariffs1_0_0Element;
    };
    interface HTMLCntFlexyViewAbdullakhBotTransitionCreateBotElement extends Components.CntFlexyViewAbdullakhBotTransitionCreateBot, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTransitionCreateBotElement: {
        prototype: HTMLCntFlexyViewAbdullakhBotTransitionCreateBotElement;
        new (): HTMLCntFlexyViewAbdullakhBotTransitionCreateBotElement;
    };
    interface HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_0_0Element extends Components.CntFlexyViewAbdullakhBotTransitionCreateBot1_0_0, HTMLStencilElement {
    }
    var HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_0_0Element: {
        prototype: HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_0_0Element;
        new (): HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_0_0Element;
    };
    interface HTMLCntFlexyViewBotAbdullakhFormCommunicationElement extends Components.CntFlexyViewBotAbdullakhFormCommunication, HTMLStencilElement {
    }
    var HTMLCntFlexyViewBotAbdullakhFormCommunicationElement: {
        prototype: HTMLCntFlexyViewBotAbdullakhFormCommunicationElement;
        new (): HTMLCntFlexyViewBotAbdullakhFormCommunicationElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSAbdullakhBenefitsBotsElement extends Components.SAbdullakhBenefitsBots, HTMLStencilElement {
    }
    var HTMLSAbdullakhBenefitsBotsElement: {
        prototype: HTMLSAbdullakhBenefitsBotsElement;
        new (): HTMLSAbdullakhBenefitsBotsElement;
    };
    interface HTMLSAbdullakhBenefitsBotsBlockElement extends Components.SAbdullakhBenefitsBotsBlock, HTMLStencilElement {
    }
    var HTMLSAbdullakhBenefitsBotsBlockElement: {
        prototype: HTMLSAbdullakhBenefitsBotsBlockElement;
        new (): HTMLSAbdullakhBenefitsBotsBlockElement;
    };
    interface HTMLSAbdullakhFormElement extends Components.SAbdullakhForm, HTMLStencilElement {
    }
    var HTMLSAbdullakhFormElement: {
        prototype: HTMLSAbdullakhFormElement;
        new (): HTMLSAbdullakhFormElement;
    };
    interface HTMLSAbdullakhFormCloseElement extends Components.SAbdullakhFormClose, HTMLStencilElement {
    }
    var HTMLSAbdullakhFormCloseElement: {
        prototype: HTMLSAbdullakhFormCloseElement;
        new (): HTMLSAbdullakhFormCloseElement;
    };
    interface HTMLSAbdullakhHeaderCenterElement extends Components.SAbdullakhHeaderCenter, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeaderCenterElement: {
        prototype: HTMLSAbdullakhHeaderCenterElement;
        new (): HTMLSAbdullakhHeaderCenterElement;
    };
    interface HTMLSAbdullakhHeaderEndElement extends Components.SAbdullakhHeaderEnd, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeaderEndElement: {
        prototype: HTMLSAbdullakhHeaderEndElement;
        new (): HTMLSAbdullakhHeaderEndElement;
    };
    interface HTMLSAbdullakhHeaderStartElement extends Components.SAbdullakhHeaderStart, HTMLStencilElement {
    }
    var HTMLSAbdullakhHeaderStartElement: {
        prototype: HTMLSAbdullakhHeaderStartElement;
        new (): HTMLSAbdullakhHeaderStartElement;
    };
    interface HTMLSAbdullakhPerformanceInformationElement extends Components.SAbdullakhPerformanceInformation, HTMLStencilElement {
    }
    var HTMLSAbdullakhPerformanceInformationElement: {
        prototype: HTMLSAbdullakhPerformanceInformationElement;
        new (): HTMLSAbdullakhPerformanceInformationElement;
    };
    interface HTMLSAbdullakhPerformanceInformationListElement extends Components.SAbdullakhPerformanceInformationList, HTMLStencilElement {
    }
    var HTMLSAbdullakhPerformanceInformationListElement: {
        prototype: HTMLSAbdullakhPerformanceInformationListElement;
        new (): HTMLSAbdullakhPerformanceInformationListElement;
    };
    interface HTMLSAbdullakhProductPresentationImgElement extends Components.SAbdullakhProductPresentationImg, HTMLStencilElement {
    }
    var HTMLSAbdullakhProductPresentationImgElement: {
        prototype: HTMLSAbdullakhProductPresentationImgElement;
        new (): HTMLSAbdullakhProductPresentationImgElement;
    };
    interface HTMLSAbdullakhProductPresentationTitleElement extends Components.SAbdullakhProductPresentationTitle, HTMLStencilElement {
    }
    var HTMLSAbdullakhProductPresentationTitleElement: {
        prototype: HTMLSAbdullakhProductPresentationTitleElement;
        new (): HTMLSAbdullakhProductPresentationTitleElement;
    };
    interface HTMLSAbdullakhTariffsInfoBlocksElement extends Components.SAbdullakhTariffsInfoBlocks, HTMLStencilElement {
    }
    var HTMLSAbdullakhTariffsInfoBlocksElement: {
        prototype: HTMLSAbdullakhTariffsInfoBlocksElement;
        new (): HTMLSAbdullakhTariffsInfoBlocksElement;
    };
    interface HTMLSAbdullakhTransitionCreateBotFollowElement extends Components.SAbdullakhTransitionCreateBotFollow, HTMLStencilElement {
    }
    var HTMLSAbdullakhTransitionCreateBotFollowElement: {
        prototype: HTMLSAbdullakhTransitionCreateBotFollowElement;
        new (): HTMLSAbdullakhTransitionCreateBotFollowElement;
    };
    interface HTMLSAbdullakhTransitionCreateBotTitleElement extends Components.SAbdullakhTransitionCreateBotTitle, HTMLStencilElement {
    }
    var HTMLSAbdullakhTransitionCreateBotTitleElement: {
        prototype: HTMLSAbdullakhTransitionCreateBotTitleElement;
        new (): HTMLSAbdullakhTransitionCreateBotTitleElement;
    };
    interface HTMLElementTagNameMap {
        "cnt-flexy-view-abdullakh-bot-consultation": HTMLCntFlexyViewAbdullakhBotConsultationElement;
        "cnt-flexy-view-abdullakh-bot-consultation-1_0_0": HTMLCntFlexyViewAbdullakhBotConsultation1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-form-communication-1_0_0": HTMLCntFlexyViewAbdullakhBotFormCommunication1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-header": HTMLCntFlexyViewAbdullakhBotHeaderElement;
        "cnt-flexy-view-abdullakh-bot-header-1_0_0": HTMLCntFlexyViewAbdullakhBotHeader1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits": HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefitsElement;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_0_0": HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-product-information": HTMLCntFlexyViewAbdullakhBotProductInformationElement;
        "cnt-flexy-view-abdullakh-bot-product-information-1_0_0": HTMLCntFlexyViewAbdullakhBotProductInformation1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-product-information-blocks": HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement;
        "cnt-flexy-view-abdullakh-bot-product-presentation": HTMLCntFlexyViewAbdullakhBotProductPresentationElement;
        "cnt-flexy-view-abdullakh-bot-product-presentation-1_0_0": HTMLCntFlexyViewAbdullakhBotProductPresentation1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-tariffs": HTMLCntFlexyViewAbdullakhBotTariffsElement;
        "cnt-flexy-view-abdullakh-bot-tariffs-1_0_0": HTMLCntFlexyViewAbdullakhBotTariffs1_0_0Element;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot": HTMLCntFlexyViewAbdullakhBotTransitionCreateBotElement;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-1_0_0": HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_0_0Element;
        "cnt-flexy-view-bot-abdullakh-form-communication": HTMLCntFlexyViewBotAbdullakhFormCommunicationElement;
        "my-component": HTMLMyComponentElement;
        "s-abdullakh-benefits-bots": HTMLSAbdullakhBenefitsBotsElement;
        "s-abdullakh-benefits-bots-block": HTMLSAbdullakhBenefitsBotsBlockElement;
        "s-abdullakh-form": HTMLSAbdullakhFormElement;
        "s-abdullakh-form-close": HTMLSAbdullakhFormCloseElement;
        "s-abdullakh-header-center": HTMLSAbdullakhHeaderCenterElement;
        "s-abdullakh-header-end": HTMLSAbdullakhHeaderEndElement;
        "s-abdullakh-header-start": HTMLSAbdullakhHeaderStartElement;
        "s-abdullakh-performance-information": HTMLSAbdullakhPerformanceInformationElement;
        "s-abdullakh-performance-information-list": HTMLSAbdullakhPerformanceInformationListElement;
        "s-abdullakh-product-presentation-img": HTMLSAbdullakhProductPresentationImgElement;
        "s-abdullakh-product-presentation-title": HTMLSAbdullakhProductPresentationTitleElement;
        "s-abdullakh-tariffs-info-blocks": HTMLSAbdullakhTariffsInfoBlocksElement;
        "s-abdullakh-transition-create-bot-follow": HTMLSAbdullakhTransitionCreateBotFollowElement;
        "s-abdullakh-transition-create-bot-title": HTMLSAbdullakhTransitionCreateBotTitleElement;
    }
}
declare namespace LocalJSX {
    interface CntFlexyViewAbdullakhBotConsultation {
        /**
          * клик по элементам компонента Consultation
         */
        "onClickOnConsultation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * данные компонента Consultation
         */
        "payload"?: SSAbdullakhConsultation;
    }
    interface CntFlexyViewAbdullakhBotConsultation1_0_0 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные компонента Consultation
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotFormCommunication1_0_0 {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные компонента FormCommunication
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotHeader {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories"?: CntFlexyViewCategoryForOwnerItemInterface;
        /**
          * клик по элементам компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotHeader1_0_0 {
        /**
          * объект с массивом меню и string для подкомпонентов header-start header-end
         */
        "categories"?: any;
        "pathToAssets"?: string;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits {
        /**
          * клик по элементам компонента PerformanceAndBenefits
         */
        "onClickOnPerformanceAndBenefits"?: (event: CustomEvent<any>) => void;
        /**
          * открытие формы связи
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0 {
        /**
          * открытие формы связи
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * объект с массивами компонентов PerformanceInformation, BenefitsBots
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotProductInformation {
        /**
          * данные из объекта для компонента ProductInformation
         */
        "ProductInformation"?: SSAbdullakhProductInformation;
        /**
          * клик по элементам компонента ProductInformation
         */
        "onClickOnProductInformation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductInformation1_0_0 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные из объекта для компонента ProductInformation
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotProductInformationBlocks {
        /**
          * объект с данными и для элементов компонента ProductInformationBlocks
         */
        "arr"?: any;
        /**
          * клик по элементам компонента ProductInformation
         */
        "onClickOnProductInformation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation {
        /**
          * клик по элементам компонента ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload"?: SSAbdullakhProductPresentation;
    }
    interface CntFlexyViewAbdullakhBotProductPresentation1_0_0 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotTariffs {
        /**
          * клик по элементам компонента Tariffs
         */
        "onClickOnTariffs"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * данные компонента Tariffs
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotTariffs1_0_0 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * данные компонента Tariffs
         */
        "payload"?: any;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot {
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnTransitionCreateBot"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload"?: SSAbdullakhTransitionCreateBot;
    }
    interface CntFlexyViewAbdullakhBotTransitionCreateBot1_0_0 {
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
        "pathToAssets"?: string;
        /**
          * массив для вывода элементов TransitionCreateBot
         */
        "payload"?: any;
    }
    interface CntFlexyViewBotAbdullakhFormCommunication {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
        /**
          * данные компонента FormCommunication
         */
        "payload"?: any;
    }
    interface MyComponent {
    }
    interface SAbdullakhBenefitsBots {
        /**
          * объект с массивом и данными BenefitsBots
         */
        "BenefitsBots"?: SSAbdullakhBenefitsBots;
        /**
          * клик по элементам компонента BenefitsBots
         */
        "onClickOnBenefitsBots"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhBenefitsBotsBlock {
        /**
          * данные переданные методом map компоненту BenefitsBotsBlock
         */
        "arr"?: any;
        /**
          * клик по элементам компонента BenefitsBots
         */
        "onClickOnBenefitsBots"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhForm {
        /**
          * данные из массива для компонента Form
         */
        "arr"?: any;
    }
    interface SAbdullakhFormClose {
        /**
          * Закрытие модального окна формы
         */
        "onCloseForm"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeaderCenter {
        /**
          * объект с данными и для элементов меню
         */
        "arr"?: AbdullakhHeaderCenter;
        /**
          * клик по элементу HeaderCenter (меню) компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhHeaderEnd {
        /**
          * клик по элементy HeaderEnd компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
        /**
          * number
         */
        "phoneNumber"?: string;
    }
    interface SAbdullakhHeaderStart {
        /**
          * объект с url logo
         */
        "logo"?: any;
        /**
          * клик по элементу HeaderStart компонента header
         */
        "onClickOnHeader"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhPerformanceInformation {
        /**
          * массив для вывода элементов PerformanceInformation
         */
        "PerformanceInformation"?: SSAbdullakhPerformanceInformation;
        /**
          * клик по элементам компонента PerformanceInformation
         */
        "onClickOnPerformanceInformation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhPerformanceInformationList {
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "PerformanceInformation"?: any;
        /**
          * объект с массивом и данными PerformanceInformationList
         */
        "endText"?: string;
        /**
          * клик по элементам компонента PerformanceInformation подкомпонента PerformanceInformationList
         */
        "onClickOnPerformanceInformation"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhProductPresentationImg {
        /**
          * массив для вывода url img в компоненете ProductPresentationImg
         */
        "img"?: any;
        /**
          * клик по элементам подкомпонента ProductPresentationImg компонента ProductPresentation
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhProductPresentationTitle {
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "arr"?: any;
        /**
          * массив для вывода элементов ProductPresentationTitle
         */
        "img"?: string;
        /**
          * клик по элементам компонента ProductPresentation подкомпонента ProductPresentationTitle
         */
        "onClickOnProductPresentation"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhTariffsInfoBlocks {
        /**
          * данные переданные методом map компоненту TariffsBlocks
         */
        "arr"?: any;
        /**
          * клик по элементам компонента Tariffs
         */
        "onClickOnTariffs"?: (event: CustomEvent<any>) => void;
        /**
          * Вызов модального окна формы
         */
        "onOpenForm"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhTransitionCreateBotFollow {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotFollow компонента TransitionCreateBot
         */
        "arr"?: any;
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnTransitionCreateBot"?: (event: CustomEvent<any>) => void;
    }
    interface SAbdullakhTransitionCreateBotTitle {
        /**
          * массив для вывода элементов подкомпонента TransitionCreateBotTitle компонента TransitionCreateBot
         */
        "arr"?: any;
        /**
          * клик по элементам компонента TransitionCreateBot
         */
        "onClickOnTransitionCreateBot"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "cnt-flexy-view-abdullakh-bot-consultation": CntFlexyViewAbdullakhBotConsultation;
        "cnt-flexy-view-abdullakh-bot-consultation-1_0_0": CntFlexyViewAbdullakhBotConsultation1_0_0;
        "cnt-flexy-view-abdullakh-bot-form-communication-1_0_0": CntFlexyViewAbdullakhBotFormCommunication1_0_0;
        "cnt-flexy-view-abdullakh-bot-header": CntFlexyViewAbdullakhBotHeader;
        "cnt-flexy-view-abdullakh-bot-header-1_0_0": CntFlexyViewAbdullakhBotHeader1_0_0;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits": CntFlexyViewAbdullakhBotPerformanceAndBenefits;
        "cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_0_0": CntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0;
        "cnt-flexy-view-abdullakh-bot-product-information": CntFlexyViewAbdullakhBotProductInformation;
        "cnt-flexy-view-abdullakh-bot-product-information-1_0_0": CntFlexyViewAbdullakhBotProductInformation1_0_0;
        "cnt-flexy-view-abdullakh-bot-product-information-blocks": CntFlexyViewAbdullakhBotProductInformationBlocks;
        "cnt-flexy-view-abdullakh-bot-product-presentation": CntFlexyViewAbdullakhBotProductPresentation;
        "cnt-flexy-view-abdullakh-bot-product-presentation-1_0_0": CntFlexyViewAbdullakhBotProductPresentation1_0_0;
        "cnt-flexy-view-abdullakh-bot-tariffs": CntFlexyViewAbdullakhBotTariffs;
        "cnt-flexy-view-abdullakh-bot-tariffs-1_0_0": CntFlexyViewAbdullakhBotTariffs1_0_0;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot": CntFlexyViewAbdullakhBotTransitionCreateBot;
        "cnt-flexy-view-abdullakh-bot-transition-create-bot-1_0_0": CntFlexyViewAbdullakhBotTransitionCreateBot1_0_0;
        "cnt-flexy-view-bot-abdullakh-form-communication": CntFlexyViewBotAbdullakhFormCommunication;
        "my-component": MyComponent;
        "s-abdullakh-benefits-bots": SAbdullakhBenefitsBots;
        "s-abdullakh-benefits-bots-block": SAbdullakhBenefitsBotsBlock;
        "s-abdullakh-form": SAbdullakhForm;
        "s-abdullakh-form-close": SAbdullakhFormClose;
        "s-abdullakh-header-center": SAbdullakhHeaderCenter;
        "s-abdullakh-header-end": SAbdullakhHeaderEnd;
        "s-abdullakh-header-start": SAbdullakhHeaderStart;
        "s-abdullakh-performance-information": SAbdullakhPerformanceInformation;
        "s-abdullakh-performance-information-list": SAbdullakhPerformanceInformationList;
        "s-abdullakh-product-presentation-img": SAbdullakhProductPresentationImg;
        "s-abdullakh-product-presentation-title": SAbdullakhProductPresentationTitle;
        "s-abdullakh-tariffs-info-blocks": SAbdullakhTariffsInfoBlocks;
        "s-abdullakh-transition-create-bot-follow": SAbdullakhTransitionCreateBotFollow;
        "s-abdullakh-transition-create-bot-title": SAbdullakhTransitionCreateBotTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cnt-flexy-view-abdullakh-bot-consultation": LocalJSX.CntFlexyViewAbdullakhBotConsultation & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotConsultationElement>;
            "cnt-flexy-view-abdullakh-bot-consultation-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotConsultation1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotConsultation1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-form-communication-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotFormCommunication1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotFormCommunication1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-header": LocalJSX.CntFlexyViewAbdullakhBotHeader & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeaderElement>;
            "cnt-flexy-view-abdullakh-bot-header-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotHeader1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotHeader1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-performance-and-benefits": LocalJSX.CntFlexyViewAbdullakhBotPerformanceAndBenefits & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefitsElement>;
            "cnt-flexy-view-abdullakh-bot-performance-and-benefits-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotPerformanceAndBenefits1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-product-information": LocalJSX.CntFlexyViewAbdullakhBotProductInformation & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductInformationElement>;
            "cnt-flexy-view-abdullakh-bot-product-information-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotProductInformation1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductInformation1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-product-information-blocks": LocalJSX.CntFlexyViewAbdullakhBotProductInformationBlocks & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductInformationBlocksElement>;
            "cnt-flexy-view-abdullakh-bot-product-presentation": LocalJSX.CntFlexyViewAbdullakhBotProductPresentation & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductPresentationElement>;
            "cnt-flexy-view-abdullakh-bot-product-presentation-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotProductPresentation1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotProductPresentation1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-tariffs": LocalJSX.CntFlexyViewAbdullakhBotTariffs & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTariffsElement>;
            "cnt-flexy-view-abdullakh-bot-tariffs-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotTariffs1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTariffs1_0_0Element>;
            "cnt-flexy-view-abdullakh-bot-transition-create-bot": LocalJSX.CntFlexyViewAbdullakhBotTransitionCreateBot & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTransitionCreateBotElement>;
            "cnt-flexy-view-abdullakh-bot-transition-create-bot-1_0_0": LocalJSX.CntFlexyViewAbdullakhBotTransitionCreateBot1_0_0 & JSXBase.HTMLAttributes<HTMLCntFlexyViewAbdullakhBotTransitionCreateBot1_0_0Element>;
            "cnt-flexy-view-bot-abdullakh-form-communication": LocalJSX.CntFlexyViewBotAbdullakhFormCommunication & JSXBase.HTMLAttributes<HTMLCntFlexyViewBotAbdullakhFormCommunicationElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "s-abdullakh-benefits-bots": LocalJSX.SAbdullakhBenefitsBots & JSXBase.HTMLAttributes<HTMLSAbdullakhBenefitsBotsElement>;
            "s-abdullakh-benefits-bots-block": LocalJSX.SAbdullakhBenefitsBotsBlock & JSXBase.HTMLAttributes<HTMLSAbdullakhBenefitsBotsBlockElement>;
            "s-abdullakh-form": LocalJSX.SAbdullakhForm & JSXBase.HTMLAttributes<HTMLSAbdullakhFormElement>;
            "s-abdullakh-form-close": LocalJSX.SAbdullakhFormClose & JSXBase.HTMLAttributes<HTMLSAbdullakhFormCloseElement>;
            "s-abdullakh-header-center": LocalJSX.SAbdullakhHeaderCenter & JSXBase.HTMLAttributes<HTMLSAbdullakhHeaderCenterElement>;
            "s-abdullakh-header-end": LocalJSX.SAbdullakhHeaderEnd & JSXBase.HTMLAttributes<HTMLSAbdullakhHeaderEndElement>;
            "s-abdullakh-header-start": LocalJSX.SAbdullakhHeaderStart & JSXBase.HTMLAttributes<HTMLSAbdullakhHeaderStartElement>;
            "s-abdullakh-performance-information": LocalJSX.SAbdullakhPerformanceInformation & JSXBase.HTMLAttributes<HTMLSAbdullakhPerformanceInformationElement>;
            "s-abdullakh-performance-information-list": LocalJSX.SAbdullakhPerformanceInformationList & JSXBase.HTMLAttributes<HTMLSAbdullakhPerformanceInformationListElement>;
            "s-abdullakh-product-presentation-img": LocalJSX.SAbdullakhProductPresentationImg & JSXBase.HTMLAttributes<HTMLSAbdullakhProductPresentationImgElement>;
            "s-abdullakh-product-presentation-title": LocalJSX.SAbdullakhProductPresentationTitle & JSXBase.HTMLAttributes<HTMLSAbdullakhProductPresentationTitleElement>;
            "s-abdullakh-tariffs-info-blocks": LocalJSX.SAbdullakhTariffsInfoBlocks & JSXBase.HTMLAttributes<HTMLSAbdullakhTariffsInfoBlocksElement>;
            "s-abdullakh-transition-create-bot-follow": LocalJSX.SAbdullakhTransitionCreateBotFollow & JSXBase.HTMLAttributes<HTMLSAbdullakhTransitionCreateBotFollowElement>;
            "s-abdullakh-transition-create-bot-title": LocalJSX.SAbdullakhTransitionCreateBotTitle & JSXBase.HTMLAttributes<HTMLSAbdullakhTransitionCreateBotTitleElement>;
        }
    }
}
